-- AlterTable
ALTER TABLE `empresas` ADD COLUMN `bairro` VARCHAR(191) NULL,
    ADD COLUMN `cep` VARCHAR(191) NULL,
    ADD COLUMN `cidade` VARCHAR(191) NULL,
    ADD COLUMN `num` VARCHAR(191) NULL,
    ADD COLUMN `rua` VARCHAR(191) NULL,
    ADD COLUMN `uf` VARCHAR(191) NULL;
